services:
  mongodb:
    image: mongodb/mongodb-community-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports: ["27017:27017"]
    volumes:
      - mongo-data:/data/db
  remix:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    volumes: [../../:/workspaces:cached]
    command: sleep infinity

volumes:
  mongo-data:
